"""Public schema exports for the Hostel Checkout API."""

from .admin import AdminProfileResponse, AdminStudentDetailResponse, DashboardResponse
from .auth import (
    CurrentUserResponse,
    LoginRequest,
    LoginResponse,
    TokenData,
    TokenResponse,
    UserResponse,
)
from .checkout import (
    CheckoutCheckin,
    CheckoutCreate,
    CheckoutDetailResponse,
    CheckoutListResponse,
    CheckoutResponse,
    QRTokenResponse,
)
from .common import (
    APIResponse,
    BaseSchema,
    ErrorDetail,
    ErrorResponse,
    PaginatedData,
    PaginationMeta,
)
from .notification import (
    NotificationCreate,
    NotificationListResponse,
    NotificationReadUpdate,
    NotificationResponse,
)
from .security import (
    QRVerificationRequest,
    QRVerificationResponse,
    SecurityProfileResponse,
    SecurityStaffListItem,
    SecurityStaffListResponse,
    SecurityStaffResponse,
    VerificationAction,
    VerifyQRRequest,
    VerifyQRResponse,
)
from .student import (
    StudentCreate,
    StudentDetailResponse,
    StudentImportError,
    StudentImportResult,
    StudentImportRow,
    StudentListItem,
    StudentListResponse,
    StudentProfileResponse,
    StudentPublic,
    StudentResponse,
    StudentUpdate,
)

__all__ = [
    "APIResponse",
    "AdminProfileResponse",
    "AdminStudentDetailResponse",
    "BaseSchema",
    "CheckoutCheckin",
    "CheckoutCreate",
    "CheckoutDetailResponse",
    "CheckoutListResponse",
    "CheckoutResponse",
    "CurrentUserResponse",
    "DashboardResponse",
    "ErrorDetail",
    "ErrorResponse",
    "LoginRequest",
    "LoginResponse",
    "NotificationCreate",
    "NotificationListResponse",
    "NotificationReadUpdate",
    "NotificationResponse",
    "PaginatedData",
    "PaginationMeta",
    "QRTokenResponse",
    "QRVerificationRequest",
    "QRVerificationResponse",
    "SecurityProfileResponse",
    "SecurityStaffListItem",
    "SecurityStaffListResponse",
    "SecurityStaffResponse",
    "StudentCreate",
    "StudentDetailResponse",
    "StudentImportError",
    "StudentImportResult",
    "StudentImportRow",
    "StudentListItem",
    "StudentListResponse",
    "StudentProfileResponse",
    "StudentPublic",
    "StudentResponse",
    "StudentUpdate",
    "TokenData",
    "TokenResponse",
    "UserResponse",
    "VerificationAction",
    "VerifyQRRequest",
    "VerifyQRResponse",
]
